name: papiana
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  analyzer: ^4.4.0
  args: ^2.3.1
  chalk: ^1.2.0
  http: ^0.13.5
  pana: ^0.21.15
  path: ^1.8.2
  safe_url_check: ^1.1.0
  tar: ^0.5.5+1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executable: papiana